#' Blend signals based on a given blending method
#'
#' @param selected_signals_corrected_positions_m_upd_ref A dataframe containing tickers and signals for the current_date
#' @param signal_selection_policy A named list containing objects to blend signals. Elements of the list are:
#' - `chosen_signals` A vector that indicates which characteristics or ml_algorithms should be used as signals
#' - `signal_positions` A named vector with same length and names as chosen_signals describing whether positions should be taken "long" or "short"
#' - `benchmark`  A character describing the benchmark to be used to calculate alphas.
#' - `signal_blending_method` A signal blending (ensemble) method. It can be accept a portfolio_construction_method, such as "EW", "SW", "RP" or "MTO" (note that cap-weighting
#' does not make sense for blending signals) or a ml_algorithm ("OLS", "GLMNET", "RF", "XGB" or "NN").
#' - `final_sb_signal`. In case of  `signal_blending_method` being a portfolio_construction_method, this variable indicates which backtest summary should be used to blend
#' signals. Possible options are: "mean_active_return", "IR", "alpha", "AP" or "treynor". For simplicity, AP will be considered as the t-stat in frequentist version.
#' - `sb_benchmark_weighting`. A character describing how the signal-blend benchmark should be built, something needed when applying constraints on signal weights.
#' Possible options are "individual" or "theme", in which case the respective dataframe in `groups_m_df_list` will be used to classify signals.
#' If individual, all signals receive the same weight. Otherwise, themes receive the same weight and signals inside the same group receive the same weight.
#' This helps when one has very unbalanced classes.
#' - `data_availability_cutoff` Minimum number of periods needed to make decisions based on backtested returns. When a signal's backtest has a length lower than this number,
#' its active returns will be assigned as 0.
#' - `signal_significance_threshold` A decimal indicating the hypothesis testing zero-alpha null-hypothesis rejection criteria. If one wants to select all chosen_signals to blend,
#' provide 1. In any case, a signal being selected demands a significant CAPM alpha.
#' - `p_correction_method`: A character describing a method to adjust alpha CAPM p-values.
#'  One of "none", holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr" or "bayesian". In case of bayesian, a bayesian hierarhical mixed effects model is fit in order to
#'  perform inference. When selecting "bayesian"the probability of direction will be used to select signals and a bayesian posterior version of the final_sb_signal
#'  will be used to give weights.
#'  In this case, the user needs to provide the following additional elements:
#'  - `chosen_informative_data`: The dataframe in priors_m_d_ref_list that will be used to build informative priors.
#'  - `set_informative_priors_on`: One of all, intercept or none. If all, priors will be built to all parameters of the mixed effects model, including variance parameters. If intercept,
#'  only location parameters will be assigned priors. Parameters not specified to receive informative priors will receive uninformative priors.
#' - `max_abs_active_individual_weight` The maximum absolute individual active weights.
#' - `max_abs_active_group_weight`: The maximum absolute group active weight used for creating group constraints in `generate_group_constraints`.
#' @param selected_signals_backtest_returns_upd_ref Optional. A backtest_df with active_returns generated by backtest_portfolio function. It should include individual backtests for each signal in signal_df
#' A object of class "factorverse_backtest" will also carry the portfolio_construction_method and signal_blending_method
#' Only necessary if signal_blending_method is equal to either RP or MTO.
#' @param priors_m_d_ref Optional. A dataframe with alpha priors for signals, containing priors for chosen_signals. Columns should match those in
#' groups_m_d_ref
#'
#' @param covariance_estimation_method One of SAM, EWMA, CC (Constant Correlation), PCA1, PCA2, Shrink_ID or Shrink_CC.
#' If NULL, blending_method can only be EW or IR
#' @param selected_benchmark_returns_upd_ref A dataframe containing date and benchmark returns columns
#' @param upper_quantile_winsorization Numeric value for upper winsorization when creating signals
#' @param lower_quantile_winsorization Numeric value for lower winsorization when creating signals
#' @return
#' @export
#'
#' @examples
blend_signals <- function(current_date,
                          signals_m_df, #Data from selected signals
                          target_m_df = NULL, #Data from targets
                          #Signal Portfolios Concentration Constraints
                          signal_selection_policy,
                          #Backtests objects
                          backtest_returns_df = NULL, selected_benchmark_returns_df = NULL,
                          #Groups
                          signals_groups_m_d_ref,
                          #Priors
                          priors_m_df_list = NULL,
                          #Covariance and P-Adjustment methods
                          covariance_estimation_method = NULL,
                          #MTO Objects
                          rp_method = "sample", n_random_portfolios = 2000, mto_port_objective = "IR",
                          #Info from past runs
                          eligible_signals = NULL, ml_walk_forward_validation_results = NULL, signal_weights = NULL,
                          #Winsorization
                          upper_quantile_winsorization = 0.975, lower_quantile_winsorization = 0.025,
                          #Verbose
                          verbose = TRUE
){


  #Initial preparations
  #########################

    ##Get signal_selection_policy objects
    signal_positions <- signal_selection_policy$signal_positions
    signal_blending_method <- signal_selection_policy$signal_blending_method
    sb_benchmark_weighting <- signal_selection_policy$sb_benchmark_weighting
    max_abs_active_individual_weight <- signal_selection_policy$max_abs_active_individual_weight
    max_abs_active_group_weight <- signal_selection_policy$max_abs_active_group_weight
    ml_parameters <- signal_selection_policy$ml_parameters

    ##Prepare objects to up-to-date version
      ###Get upd ref
      upd_ref <- which(as.Date(signals_m_df$dates,  format = "%Y-%m-%d") <= current_date) #What references correspond up to this date?

      ###m_upd_ref
      ####signals_m_upd_ref
      signals_m_upd_ref <- signals_m_df[upd_ref, ]

      ####target_m_upd_ref
      target_m_upd_ref <- target_m_df[upd_ref,]

      ####priors_m_upd_ref_list
      try(priors_m_upd_ref_list <- lapply(priors_m_df_list, function(x){if(is.data.frame(x)) return(x[which(x$dates <= current_date), ]) else x}))
      ###Select Priors
      chosen_informative_data <- signal_selection_policy$chosen_informative_data ##Get chosen informative_prior_data
      try(selected_priors_informative_data_m_upd_ref <- priors_m_upd_ref_list[[chosen_informative_data]], silent = TRUE)

      ###upd_ref
      ####returns_df objects
      try(backtest_returns_upd_ref <-  backtest_returns_df[which(backtest_returns_df$dates <= current_date), ])#Only dates before current_date
      try(selected_benchmark_returns_upd_ref <- selected_benchmark_returns_df[which(selected_benchmark_returns_df$dates <= current_date), ]) #Only dates before current_date

    ##Select signals and respective backtests based on user choice
      selected_signals_and_backtest_list <- select_and_correct_signals(
        #Signal Selection Policy
        signal_selection_policy = signal_selection_policy,
        #Signals DF
        signals_m_upd_ref = signals_m_upd_ref,
        #Signals backtest
        backtest_returns_upd_ref = backtest_returns_upd_ref
      )

      ##Selected signals corrected positions
      selected_signals_corrected_positions_m_upd_ref <- selected_signals_and_backtest_list$selected_signals_corrected_positions_m_upd_ref
      ###Get selected_signals_corrected_positions_m_d_ref
      d_ref <- which(selected_signals_corrected_positions_m_upd_ref$dates == current_date)
      selected_signals_corrected_positions_m_d_ref <- selected_signals_corrected_positions_m_upd_ref[d_ref,]

      ##Selected signals backtest returns
      selected_signals_backtest_returns_upd_ref <- selected_signals_and_backtest_list$selected_signals_backtest_returns_upd_ref

        ###Check if both are contemplated in signals_groups
        if(any(!colnames(dplyr::select(selected_signals_corrected_positions_m_d_ref, -id, -tickers, -dates)) %in% signals_groups_m_d_ref$tickers)){
          stop("all selected signals (with corrected positions) should have a theme classification in signals_groups_m_d_ref")
        }
        if(!is.null(selected_signals_backtest_returns_upd_ref)){
          if(
            any(!colnames(dplyr::select(selected_signals_backtest_returns_upd_ref, -dates)) %in% signals_groups_m_d_ref$tickers)){
            stop("all selected signals in backtests (with corrected positions) should have a theme classification in signals_groups_m_d_ref")
         }
        }

      #########################


      #Define signal eligibility
      ############################
      ###Check if eligible signals were alread defined
      if(is.null(eligible_signals)){
        ##Check for p_correction_method and backtest_returns_d_ref
        if(!is.null(selected_signals_backtest_returns_upd_ref)){
          if(verbose){
            cat("\n")
            cat(crayon::yellow(paste0("Defining signal eligibility following ", signal_selection_policy$p_correction_method, " method")))
          }
          ###Create signal_universe_d_ref
          signal_eligibility_results_list <- define_signal_eligibility(
            #Backtests
            selected_signals_backtest_returns_upd_ref = selected_signals_backtest_returns_upd_ref,
            selected_benchmark_returns_upd_ref = selected_benchmark_returns_upd_ref,
            #Signal selection policy
            signal_selection_policy = signal_selection_policy,
            #Groups
            signals_groups_m_d_ref = signals_groups_m_d_ref,
            #Priors
            selected_priors_informative_data_m_upd_ref = selected_priors_informative_data_m_upd_ref
          )
          ###Get results
          signal_universe_m_d_ref <- signal_eligibility_results_list$signal_universe_m_d_ref
          bayesian_fit_list <- signal_eligibility_results_list$bayesian_fit_list

          if(verbose){
            cat("\n")
            cat(crayon::green(paste0("Eligible signals defined: ")))
            cat(signal_universe_m_d_ref$tickers[which(signal_universe_m_d_ref$is_eligible == 1)])
          }
          #In case there is no backtest avaiable, generate signal signal_universe_m_d_ref
        } else {
          signal_universe_m_d_ref <- data.frame(tickers = colnames(selected_signals_corrected_positions_m_upd_ref)[-c(1:3)])
          signal_universe_m_d_ref$is_eligible <- rep(1, nrow(signal_universe_m_d_ref))
        }

        ##Eligible signals
        eligible_signals <- signal_universe_m_d_ref %>% dplyr::filter(is_eligible == 1) %>% dplyr::select(tickers)
      }

      #########################

      ###Define Signal Weights or ML model
      ####################################
      ###Check if signal_weights or ml_walk_forward_validation_results have already been provided
      if(all(is.null(signal_weights), is.null(ml_walk_forward_validation_results))){
        if(verbose){
          cat("\n")
          cat(crayon::yellow(paste("Setting signal weights for blending following the", signal_blending_method, "method")))
          cat("\n")
        }

        #In case of backtest derived weights
        if(signal_blending_method != "ML"){

          ##Set Signal Blend Portfolio Weights
          signal_universe_m_d_ref <- set_portfolio_weights(
            #Signal universe object
            universe_m_d_ref = signal_universe_m_d_ref,
            #Signal Blending method
            portfolio_construction_method = signal_blending_method,
            #Groups
            groups_m_d_ref = signals_groups_m_d_ref,
            #Returns sample
            returns_upd_ref = selected_signals_backtest_returns_upd_ref,
            #Covariance Estimation Method
            covariance_estimation_method = covariance_estimation_method, covariance_matrix_sample_size = NULL, #Sample size to estimate cov matrix (NULL => full period)
            #Number of random portfolios to generate for numeric optimization
            n_random_portfolios = n_random_portfolios,
            #RandomPorts method
            rp_method = rp_method,
            #What to optimize? #Objective for MTO Optimization
            mto_port_objective = mto_port_objective,
            #Set concentration constraint policy for signals
            concentration_constraint_policy = list(
              benchmark = sb_benchmark_weighting, #Reference benchmark
              max_abs_active_individual_weight = max_abs_active_individual_weight, #Max abs active individual weight
              max_abs_active_group_weight = max_abs_active_group_weight), #Max group weight for signal
            #Winsorization
            lower_quantile_winsorization = lower_quantile_winsorization, #Quantiles for winsorization
            upper_quantile_winsorization = upper_quantile_winsorization #Quantiles for winsorization
          )

      #Get signal weights
      signal_weights <- signal_universe_m_d_ref$weights

  } else {}
        #In case of ML model
        if(signal_blending_method == "ML"){

          #ML WF Backtest
          #############################

          #Get args
          #############################
          ##Get features and target objects for ML model
          ###target
          target_fwd <- ml_parameters$target_fwd #OOS period of outcome
          target_fwd_name <- ml_parameters$target_fwd_name #Name of target
          #Note that this series contains only data up to current_date
          target_m_df <- target_m_upd_ref[order(target_m_upd_ref$dates),] #Re-order
          target_m_df <- target_m_df %>% dplyr::select(id, tickers, dates, {{target_fwd_name}}) #Get onl fwd
          target_dates <- unique(target_m_upd_ref$dates)
          fwd_looking_dates <- target_dates[(length(target_dates) - target_fwd + 1):length(target_dates)] #dates not avaiable back then
          target_m_df[which(target_m_df$dates == fwd_looking_dates), {{target_fwd_name}}] <- NA

          ###features
          features_m_df <- selected_signals_corrected_positions_m_upd_ref %>%
            dplyr::select(id, tickers, dates, all_of(eligible_signals$tickers)) #Note that this series contains only data up to current_date for eligible signals
          features_m_df <- features_m_df[order(features_m_df$dates),] #Order by date

          ###Set dates objects
          dates_m_vector <- unique(features_m_df$dates)
          ###training_sample_size
          training_sample_size <- round(ml_parameters$training_sample_rate * length(dates_m_vector), 0)
          ###validation_sample_size
          validation_sample_size <- length(dates_m_vector) - training_sample_size
          ###rebalancing_months
          rebalancing_months <- lubridate::month(dates_m_vector[(training_sample_size + validation_sample_size)])
          split_method <- ifelse(is.null(ml_parameters$split_method), "expanding", ml_parameters$split_method)

          ###Modeling parameters
          ###Algorithm choices
          ml_algorithm <- ml_parameters$ml_algorithm #ML Algorithm
          huber_delta <- ifelse(is.null(ml_parameters$huber_delta), 1,  ml_parameters$huber_delta) #If not set by user, pass as 1
          quantile_tau <- ifelse(is.null(ml_parameters$quantile_tau), 0.5, ml_parameters$quantile_tau) #If not set by user, pass as 0.5
          custom_objective <- ifelse(is.null(ml_parameters$custom_objective), "squared_error",  ml_parameters$custom_objective) #Custom Objective

          ###Hyperparameter tuning
          chosen_eval_metric <- ml_parameters$chosen_eval_metric #Chosen eval metric for validation
          hyper_grid_domain_list <- ml_parameters$hyper_grid_domain_list #Hyperparameter domain
          tuning_method <- ml_parameters$tuning_method #Tuning method
          n_iter <- ml_parameters$n_iter #Number of iterations
          ###Bayes Opt
          k_iter <- ml_parameters$k_iter
          acq <- ifelse(is.null(ml_parameters$acq), "ucb", ml_parameters$acq)  #Acquisition Function
          init_points <- ml_parameters$init_points #Initial points to evaluate chosen eval

          ###Others
          early_stop <- ml_parameters$early_stop #Early stop
          keras_architecture_parameters <- ml_parameters$keras_architecture_parameters
          parallel <- ifelse(is.null(ml_parameters$parallel), TRUE, ml_parameters$parallel)


          #############################

          #Fit ML model
          #############################
          ml_walk_forward_validation_results <- ml_walk_forward_validation(
            #Objects
            features_m_df = features_m_df, target_m_df = target_m_df, dates_m_vector = dates_m_vector,
            target_fwd = target_fwd, target_fwd_name = target_fwd_name,
            #Training sample
            training_sample_size = training_sample_size, validation_sample_size = validation_sample_size,
            rebalancing_months = rebalancing_months, split_method = split_method,
            #Choice of ML algorithm
            ml_algorithm = ml_algorithm,
            #Loss/Eval Functions and Related
            custom_objective = custom_objective, chosen_eval_metric = chosen_eval_metric, huber_delta = huber_delta, quantile_tau =quantile_tau,
            #Hyperparameter tuning Inputs
            hyper_grid_domain_list = hyper_grid_domain_list, tuning_method = tuning_method, n_iter = n_iter,
            k_iter = k_iter, acq = acq, init_points = init_points, early_stop = early_stop,
            #Keras architecture Parameters
            keras_architecture_parameters = keras_architecture_parameters,
            #Misc
            show_plots = FALSE, verbose = TRUE, parallel = parallel
          )

  } else {}

      }
      #########################

      ##Get final signals for current month
      #########################

      #Set final signal
      final_signal_results_list <- set_final_signal(
        #Information on signals
        selected_signals_corrected_positions_m_d_ref = selected_signals_corrected_positions_m_d_ref,
        #Info from past or current runs
        eligible_signals = eligible_signals, #Signals deemed eligible
        signal_weights = signal_weights, #For no ML approach
        ml_walk_forward_validation_results = ml_walk_forward_validation_results,
        #Winsorization for final signal compute
        upper_quantile_winsorization = upper_quantile_winsorization, lower_quantile_winsorization = lower_quantile_winsorization
      )

        ##Get objects
        stock_universe_m_d_ref <- final_signal_results_list$selected_signals_corrected_positions_m_d_ref
        ml_predictions <- final_signal_results_list$ml_predictions
        new_features_m_d_ref <- final_signal_results_list$new_features_m_d_ref

      ############################

      #Join results
      signal_results_list <- list()
      try(signal_results_list$signal_universe_m_d_ref <- signal_universe_m_d_ref, silent = TRUE)
      signal_results_list$stock_universe_m_d_ref <- stock_universe_m_d_ref
      signal_results_list$eligible_signals <- eligible_signals
      signal_results_list$ml_walk_forward_validation_results <- ml_walk_forward_validation_results
      signal_results_list$signal_weights <- signal_weights
      try(signal_results_list$bayesian_fit_list <- bayesian_fit_list, silent = TRUE)
      try(signal_results_list$ml_predictions <- ml_predictions, silent = TRUE)
      try(signal_results_list$new_features_m_d_ref <- new_features_m_d_ref, silent = TRUE)

      return(signal_results_list)

}

