#' Fit a Bayesian Hierarchical Regression Model and Summarize Posterior Metrics
#'
#' This function fits a Bayesian hierarchical regression model using the `brms` package and computes posterior summary
#' statistics for signal-level metrics. The model captures signal clustering within themes and provides detailed
#' posterior metrics for use in performance analysis.
#'
#' @param signal_universe_m_d_ref A data frame containing the signal universe. This data frame should include:
#'   - `tickers`: Unique identifiers for signals.
#'   - `is_eligible`: A logical column indicating if a signal is eligible for modeling.
#'   - `final_signal`: Finalized signals to be used for modeling.
#'
#' @param selected_backtest_returns_corrected_positions_upd_ref A data frame containing the backtest returns data for various signals.
#'   - The first column should include dates.
#'   - Remaining columns represent signals (e.g., tickers) and their respective active returns.
#'
#' @param selected_market_factor_proxy_vector_upd_ref A numeric vector containing benchmark returns data. The vector will be recycled
#'   to match the length of the backtest returns data.
#'
#' @param elected_priors An object of class `brmsprior` containing priors for the Bayesian model, such as those generated by the
#'   \code{\link{get_priors_from_informative_data}} function or provided directly by the user.
#'
#' @param signal_themes_m_d_ref A data frame containing metadata about signals. This data frame should include:
#'   - `tickers`: Signal identifiers matching those in `selected_backtest_returns_corrected_positions_upd_ref`.
#'   - `theme`: Group membership for each signal, defining the clusters for the Bayesian hierarchical model.
#'   - `dates`: Dates corresponding to the backtest data.
#'   This input ensures proper alignment between signals and their associated themes.
#'
#' @param model_spec_theme_level A character string specifying the desired Bayesian model structure.
#'   Options include:
#'   - `"random_intercept"`: Includes random effects for the intercept at the theme level.
#'   - `"fixed_intercepts"`: Uses fixed intercepts for each theme.
#'   - `"fixed_intercepts_and_slopes"`: Includes fixed intercepts and slopes for each theme.
#'   - `"none"`: Omits theme-level intercepts but includes random effects at the theme:signal level.
#'
#' @param verbose A logical indicating whether to display progress messages during the model fitting process. Defaults to `TRUE`.
#' @param parallel A logical indicating whether to enable parallel computation using `future`. Defaults to `TRUE`.
#'
#' @return A named list containing:
#'   - `bayesian_model`: A `brmsfit` object containing the fitted Bayesian model. This object includes posterior distributions,
#'     parameter estimates, diagnostics, and other details of the model fit.
#'   - `posterior_signal_universe_m_d_ref`: A data frame containing the updated `signal_universe_m_d_ref` with posterior summary statistics.
#'
#' @details
#' The function performs the following steps:
#' 1. **Preprocessing**: Converts the backtest returns data into long format, merges metadata about signals and themes,
#'    and adds the market factor proxy.
#' 2. **Formula Specification**: Defines the Bayesian model formula based on the chosen `model_spec_theme_level`.
#' 3. **Model Fitting**: Fits the Bayesian model using the `brm` function from the `brms` package, incorporating the
#'    provided priors and prepared data.
#' 4. **Posterior Summarization**: Extracts posterior draws and computes signal-level metrics such as alphas, betas,
#'    sigmas, active returns, tracking errors, information ratios (IR), appraisal ratios (AP), and Treynor ratios.
#'    Updates the `signal_universe_m_d_ref` data frame with these metrics.
#'
#' This hierarchical approach allows the model to capture both global (theme-level) and local (signal-level) effects
#' while leveraging the flexibility of Bayesian regression. The inclusion of posterior metrics enables deeper
#' performance analysis of signals.
#'
#' @examples
#' \dontrun{
#' # Example usage
#' results <- fit_bayesian_model(
#'   signal_universe_m_d_ref = signal_universe_data,
#'   selected_backtest_returns_corrected_positions_upd_ref = backtest_data,
#'   selected_market_factor_proxy_vector_upd_ref = benchmark_data,
#'   elected_priors = priors_list,
#'   signal_themes_m_d_ref = signal_metadata,
#'   model_spec_theme_level = "random_intercept",
#'   verbose = TRUE,
#'   parallel = TRUE
#' )
#'
#' # Access the Bayesian model and posterior metrics
#' bayesian_model <- results$bayesian_model
#' posterior_metrics <- results$posterior_signal_universe_m_d_ref
#' }
#'

fit_bayesian_model <- function(signal_universe_m_d_ref, selected_backtest_returns_corrected_positions_upd_ref, selected_market_factor_proxy_vector_upd_ref, #Data
                               elected_priors, signal_themes_m_d_ref, model_spec_theme_level, #Hierarhical Model spec
                               chains, iter, warmup, thin, seed, adapt_delta, #brm parameters (Monte Carlo Markov Chains - MCMC settings)
                               verbose, parallel){

  #Prepare objects
  ######################
  ##Add market_factor_proxy
  selected_backtest_returns_corrected_positions_upd_ref$market_factor_proxy <- selected_market_factor_proxy_vector_upd_ref #R will recycle

  ##Melt
  selected_backtest_returns_corrected_positions_upd_ref <- tidyr::pivot_longer(
    selected_backtest_returns_corrected_positions_upd_ref,
    cols = -c(dates, market_factor_proxy),
    names_to = "tickers", #Rename to match priors
    values_to = "active_return"
    ) %>%
    dplyr::select(dates, tickers, active_return, market_factor_proxy) %>% as.data.frame() #Reorder columns


  ##Add theme
  selected_backtest_returns_corrected_positions_upd_ref <- dplyr::left_join(
    selected_backtest_returns_corrected_positions_upd_ref,
    signal_themes_m_d_ref %>% dplyr::select(tickers, theme), by = "tickers")

  #Fit brm
  ########################
    ###Create formula
    brm_formula <-
      switch(model_spec_theme_level,
             # Random effects on intercept on theme level
             "random_intercept" = brms::brmsformula(active_return ~ market_factor_proxy + (1 | theme) + (1 + market_factor_proxy | theme:tickers)),
             "fixed_intercepts" = brms::brmsformula(active_return ~ 0 + theme + market_factor_proxy + (1 + market_factor_proxy | theme:tickers)),
             "fixed_intercepts_and_slopes" = brms::brmsformula(active_return ~ 0 + theme + theme:market_factor_proxy + (1 + market_factor_proxy | theme:tickers)),
             "none" = brms::brmsformula(active_return ~ market_factor_proxy + (1 + market_factor_proxy | theme:tickers))
      )

  ###Fit model
  brm_model <- brms::brm(
    brm_formula,
    #Priors
    prior = elected_priors,
    #Data
    data = selected_backtest_returns_corrected_positions_upd_ref,
    #Parallelization
    future = parallel,
    #MCMC
    chains = chains, iter = iter, warmup = warmup, thin = thin, seed = seed,
    control = list(adapt_delta = adapt_delta)
  )
  ########################

  #Get Posteriors
  #############################################

  #Update signal_universe_m_d_ref with posterior statistics
  posteriors_results_list <- summarize_posteriors_draws(
    brm_model = brm_model, #brms model
    signal_universe_m_d_ref = signal_universe_m_d_ref, #Signal Universe
    model_spec_theme_level = model_spec_theme_level, #Model spec
    signal_themes_m_d_ref = signal_themes_m_d_ref) #Groups

  #############################################

  return(posteriors_results_list)
}
