#' Create a risk parity portfolio
#'
#' @param universe_m_d_ref A dataframe with tickers, is_eligible and final_signal columns generated by filter_stock_universe
#' @param returns_xts_upd_ref A dataframe in which columns represent tickers present in universe_m_d_ref and row represent periods
#' It should include all stocks in current_stock_universe and a dates column with at least cov_matrix_sample_size periods before current_date
#' @param covariance_matrix The covariance matrix of all eligible stocks in universe_m_d_ref.
#' @return
#' @export
#'
#' @examples
create_risk_parity_portfolio <- function(universe_m_d_ref, covariance_matrix, rp_method = "cyclical-spinu", verbose = TRUE){

  #Message
  if(verbose){
    tictoc::tic()
    cat("\n")
    cat("Deriving weights through RP...")
  }

  #Create rp_weights object
  rp <- riskParityPortfolio::riskParityPortfolio(Sigma = covariance_matrix, method_init = rp_method)
  rp_weights <- data.frame(tickers = names(rp$w), weights = rp$w) #get weights and relative risk contribution

  #Merge with current_stock_universe
  universe_m_d_ref <- dplyr::left_join(universe_m_d_ref, rp_weights, by = "tickers")

  #Replace NAs with zeros
  universe_m_d_ref[which(is.na(universe_m_d_ref$weights)),"weights"] <- 0

  #Message
  if(verbose){
    cat("\n")
    cat(crayon::green(paste("Risk Parity weights succesfully defined")))
    cat("\n")
    elapsed_time <- tictoc::toc()
  }


  #Return
  rp_results_list <- list(
    universe_m_d_ref = universe_m_d_ref,
    weights = universe_m_d_ref$weights,
    rel_risk_contr = rp$relative_risk_contribution
  )

  return(rp_results_list)
}
