#' Declare global variables used in NSE to avoid R CMD check notes
#'
#' @name globalVariables_nse
#' @keywords internal
utils::globalVariables(c(
  ".chain", ".data", ".draw", ".interval", ".iteration", ".point", ".prediction",
  ":=", "BacktestRow", "Calc_Stat", "Category", "Cluster", "Coefficient",
  "Column", "Component", "Composition_Group", "Contribution", "Contribution_Type",
  "Count", "Cumulative", "Cumulative_End", "Cumulative_Start", "Date", "Delta",
  "Density", "End", "Estimate", "Feature", "Frequency", "From", "Freq", "Group",
  "Hyperparameter", "Importance", "Market Factor Fixed Effect", "MaxAllowed",
  "Mean_Contribution", "Midpoint", "MinAllowed", "Name", "New_Group", "Non_NA_Count",
  "Objective", "Parameter", "PrevCumulative", "Pseudo_huber_error", "Quantile",
  "Quantile_error", "Relative_order_size", "Sd", "Sd_value", "Sign", "Specific_risk",
  "Squared_error", "Start", "Target", "Theme Fixed Effect", "Theme Random Effect",
  "Ticker Random Intercept", "Ticker Random Slope", "Times_eligible", "To",
  "TotalContribution", "Total_Eligible", "Total_Periods", "Total_Tickers",
  "Total_variance", "Type", "Val", "Value", "Variance", "Var1", "Var2", "Weight",
  "X", "Xmax", "Xmin", "Y", "Ymax", "Ymin", "adjusted_importance", "alpha",
  "alpha_difference_from_overall_mean", "alpha_fixed_effect", "alpha_fixed_effect_sd",
  "alpha_p_value", "alpha_random_effect", "alpha_se", "assetRow", "avg_ir",
  "avg_sharpe", "avg_val", "backtest", "backtest_label", "benchmark_weight",
  "benchmark_weights", "beta_difference_from_overall_mean", "beta_fixed_effect",
  "beta_fixed_effect_sd", "beta_random_effect", "b_market_factor_proxy",
  "b_Intercept", "cap_score", "change_date", "chosen_eval_metric", "coef",
  "column", "cons_oos", "cor_theme:tickers__Intercept__market_factor_proxy",
  "count", "cov", "cov2cor", "cov_tickers_intercept_slope", "dates", "delisted",
  "density", "does_liquidity_meets_turnover_cap_rule", "draws", "early_stopping_rounds",
  "eligible_tickers", "end", "error", "exp_ret_score", "feature", "feature_value",
  "fill_type", "fixed_effect", "fixed_effect_name", "fixed_effect_p_values",
  "fixed_effect_sd", "from", "fwd_return_1m", "get_sb_backtest_config", "group",
  "has_not_na", "importance", "individual_alpha", "individual_beta", "info_ratio",
  "input", "is_eligible", "label", "listed", "liquidity_classification",
  "liquidity_floor", "market_factor_proxy", "max_last", "max_val", "mean_market_factor_proxy",
  "median", "min_first", "min_val", "n_assets", "n_obs", "name", "new_group",
  "new_perm_id", "new_ticker", "new_tickers_first_quote", "new_tickers_last_quote",
  "normalized_importance", "obs", "old", "old_perm_id", "old_ticker",
  "old_tickers_first_quote", "old_tickers_last_quote", "overall_alpha_mean_by_dates",
  "overall_beta_mean_by_dates", "overall_mean", "overall_sigma_mean_by_dates",
  "parameter", "period_return", "perm_id", "posterior_alpha_t_stat",
  "posterior_cor_r_alpha_beta", "posterior_geom_mean_ret", "posterior_individual_alpha",
  "posterior_individual_alpha.lower", "posterior_individual_alpha.upper",
  "posterior_individual_beta", "posterior_individual_beta.lower",
  "posterior_individual_beta.upper", "posterior_r_theme_alpha",
  "posterior_r_tickers_alpha", "posterior_r_tickers_beta", "posterior_sigma",
  "pred", "pre_eligible_assets", "prior", "priors_m_df", "pseudo_huber_error",
  "quantile", "quantile_error", "r_theme", "r_theme:tickers", "r_tickers_intercept",
  "r_tickers_slope", "relevant_indices_signal", "rel_risk_contr", "returns",
  "row_id", "sb_backtest", "sb_backtest_results", "sd", "sd_theme__Intercept",
  "sd_theme:tickers__Intercept", "sd_theme:tickers__market_factor_proxy",
  "series", "setNames", "sharpe_ratio", "sigma", "sigma_difference_from_overall_mean",
  "specific_risk", "sq_error", "start", "sum_w", "squared_error",
  "supressWarnings", "target", "theme", "theme Fixed Effect", "theme_alpha_random_effect",
  "theme_sb", "theme_sb_bench_weights", "theme_ss_bench_weights",
  "theme_tickers", "theme:tickers", "ticker", "tickers", "tickers_first_quote",
  "tickers_last_quote", "tickers_term", "times_eligible", "to", "total_cost",
  "total_eligible", "total_periods", "total_tickers", "total_variance",
  "turnover_cap_rule", "two_moment", "type", "untraded", "untrd_not_only_NA_FALSE",
  "untrd_not_only_NA_TRUE", "updated_port_weights", "upper", "val", "value",
  "variable", "var_sigma", "var_theme_intercept", "var_tickers_intercept",
  "var_tickers_slope", "variance", "was_in_old_portfolio", "weights",
  "x", "xmax", "xmin", "y", "ymax", "ymin", "year", "year_first", "year_last",
  "id", "is_in_buffered_quantile_range", "bop_port_weights", ".", "daily_vol",
  "eop_port_weights", "delta", "relative_order_size", "theme_id", "Metric", "max_weight",
  "min_weight", "testing_dates_range", "df", "t_value", "theme_term", "theme_fixed_effect",
  "fixed_effect_value", "posterior_theme_alpha", "posterior_theme_alpha.lower", "posterior_theme_alpha.upper",
  "posterior_theme_beta", "posterior_theme_beta.lower", "posterior_theme_beta.upper", ".width", "posterior_specific_risk",
  "hyperparameter", "lower", "Correlation", "bin_label"
))

