
#' Applies a buffer rule based on the creation of a buffer zone for illiquid stocks
#'
#' This rule is applied to reduce portfolio turnover and transaction costs.
#'
#' @param signals_m_d_ref A data frame of selected signals generated by the `generate_signal_matrix` function.
#' @param top_stocks_quantile_buffer Numeric value indicating the quantile to apply the buffer rule.
#'  Stocks in this quantile and pre-rebalancing portfolio will be included in the `filtered_stock_universe` if they meet the buffer rule policy.
#' @param portfolio_weights_m_lstd_ref  A data frame containing columns for id, tickers, dates and weights from the old portfolio (pre-rebalancing)
#' All tickers in current stock universe must have a unique correspondence in this data frame.
#' @param liquidity_m_d_ref A data frame (similar to `features_m_df`) containing columns for id, tickers, dates, and one or more market liquidity measures (e.g., inflation-adjusted mean financial volume).
#' All tickers in current stock universe must have a unique correspondence in this data frame.
#' @param liquidity_floor_cutoffs_list A list of named vectors containing cutoff values for liquidity metrics specified in `liquidity_m_d_ref`.
#' The names should match the metrics and values should be the minimum acceptable values (adjust for inflation)
#' Elements should be: "micro_caps", "small_caps", "mid_caps" and "large_caps"
#' Classification should be in ascending order (from lest liquid to most liquid) for all metrics.
#' @param buffer_rule Character string specifying the buffer rule target (one of "micro_caps", "small_caps", "mid_caps", "large_caps", "mega_caps").
#' Stocks that are less liquid than `buffer_rule` and that are included in the buffer_zone will be promoted.
#' Stocks meeting this rule will be included in the `filtered_stock_universe` even if they fail the liquidity floor rule.
#'
#' @return
#' @export
#'
#' @examples
apply_buffer_rule <- function(signals_m_d_ref, top_assets_quantile_buffer,  portfolio_weights_m_lstd_ref,
                              liquidity_m_d_ref, liquidity_floor_cutoffs_list, buffer_rule, verbose = TRUE){

  ##Checks
  ###########
  ##Check possibilities for buffer_rule
  if(!buffer_rule %in% c("micro_caps", "small_caps", "mid_caps", "large_caps", "mega_caps")){
    stop("buffer_rule not supported")
  }


  ############

  ###Get objects
  ################
  ##Buffer Rule DF
  buffer_rule_m_d_ref <- signals_m_d_ref #Init dataframe
  ##Get liquidity metrics names
  liquidity_metrics <- names(liquidity_floor_cutoffs_list[[1]]) #Get name of metrics

  ################

  ###Buffer Zone
  #################
  #Is in top quantile buffer?
  buffer_rule_m_d_ref$is_in_top_quantile_buffer <- ifelse(signals_m_d_ref[,"final_signal"] >= quantile(signals_m_d_ref[,"final_signal"], top_assets_quantile_buffer), 1L,0L) #Check rule

  #Was in old_portfolio?
  buffer_rule_m_d_ref <- dplyr::left_join(buffer_rule_m_d_ref, portfolio_weights_m_lstd_ref, by = "tickers") %>% #Get old weights
    dplyr::select(tickers, is_in_top_quantile_buffer, old_portfolio_weights) #Select only those info

  ##Replace NAs (new stocks) for 0
  buffer_rule_m_d_ref$old_portfolio_weights[which(is.na(buffer_rule_m_d_ref$old_portfolio_weights))] <- 0

  #Create column
  buffer_rule_m_d_ref$was_in_old_portfolio <- ifelse(buffer_rule_m_d_ref$old_portfolio_weights > 0, 1L, 0L)

  #################

  ###Applies buffer rule
  #################
  ##Meets buffer rule policy?
  buffer_rule_m_d_ref$does_liquidity_meets_buffer_rule <- ifelse(
    classify_stock_liquidity(
      liquidity_floor_cutoffs_list = liquidity_floor_cutoffs_list, #Liquidity classficiation
      liquidity_m_df = liquidity_m_d_ref, #Liquidity data
      liquidity_floor_rule = buffer_rule, #Classification
      apply_liquidity_floor_rule = FALSE,
      filter_out_liquidity_floor_rule = FALSE
    )$liquidity_classification == buffer_rule, 1L, 0) #Does stock meet buffer rule?

  ##Apply buffer rule
  buffer_rule_m_d_ref$buffer_rule <-
    apply(buffer_rule_m_d_ref %>% dplyr::select(is_in_top_quantile_buffer, was_in_old_portfolio, does_liquidity_meets_buffer_rule), 1, function(row){
      all(row == 1) #Does stock meets all requirements for buffer rule application?
    }) %>% as.integer()

  #################

  #Message
  if(verbose){
    cat("\n")
    cat(paste0("The following ", buffer_rule, " belong to the buffer_zone and will be kept:"))
    cat("\n")
    cat(buffer_rule_m_d_ref$tickers[which(buffer_rule_m_d_ref$buffer_rule == 1)])
    cat("\n")
  }


  ###Return object
  return(buffer_rule_m_d_ref)

}
