#' Create a risk parity portfolio
#'
#' @param universe_m_d_ref A dataframe with tickers, is_eligible and final_signal columns generated by filter_stock_universe
#' @param covariance_matrix The covariance matrix of all eligible stocks in universe_m_d_ref.
#' @param rp_method The method used to calculate the risk parity weights. Default is "cyclical-spinu". See riskParityPortfolio::riskParityPortfolio for more options.
#' @param exp_ret_score_tilt The numeric tilt to apply to the risk parity weights based on the exp_ret_score column in universe_m_d_ref. If NULL, no tilt is applied.
#' @param verbose If TRUE, will print messages to the console
create_risk_parity_portfolio <- function(universe_m_d_ref, covariance_matrix,
                                         rp_method = "cyclical-spinu",
                                         exp_ret_score_tilt = NULL,
                                         verbose = TRUE){

  # Initial Setup---------------------------------------------------------------

   ## Message
   if(verbose){
     tictoc::tic()
     cat("\n")
     cat("Deriving weights through RP...")
     cat("\n")
     cat("RP method: ", rp_method, "\n")
     if (!is.null(exp_ret_score_tilt)) cat("Exp Ret Score Tilt: ", exp_ret_score_tilt, "\n")
   }


  # Tilted RP-------------------------------------------------------------------
  if (!is.null(exp_ret_score_tilt)){

    ## Create rp_weights object depending on existence of a exp_ret_score_tilt

      ### Defensively check if exp_ret_score column exists in universe_m_df
      if (!("exp_ret_score" %in% colnames(universe_m_d_ref))) {
        stop("exp_ret_score column is not present in universe_m_d_ref")
      }

      ### Apply rp with exp_ret_score_tilt
      rp <- riskParityPortfolio::riskParityPortfolio(
        #### Cov
        Sigma = covariance_matrix,
        #### Tilt
        mu = universe_m_d_ref$exp_ret_score[
          match(rownames(covariance_matrix), universe_m_d_ref$tickers)],
        lmd_mu = exp_ret_score_tilt,
        #### Method
        method_init = rp_method
      )

  # Traditional RP---------------------------------------------------------------
  } else {

    ### Apply rp without exp_ret_score_tilt
    rp <- riskParityPortfolio::riskParityPortfolio(
      Sigma = covariance_matrix,
      method_init = rp_method
    )

  }

  # Return weights---------------------------------------------------------------
    ## Get weights and RRC
    rp_weights <- data.frame(tickers = names(rp$w), weights = rp$w)

    ## Merge with current_stock_universe
    universe_m_d_ref <- dplyr::left_join(universe_m_d_ref, rp_weights, by = "tickers")

    ## Replace NAs with zeros
    universe_m_d_ref[which(is.na(universe_m_d_ref$weights)),"weights"] <- 0

    ## Check for weights different from 1
    if (abs(sum(universe_m_d_ref$weights) - 1) > 0.01){
      stop("Weights do not sum to 1")
    }

    ## Message
    if(verbose){
      cat("\n")
      cat(crayon::green(paste("Risk Parity weights succesfully defined")))
      cat("\n")
      tictoc::toc()
    }

    ## Return
    rp_results_list <- list(
      universe_m_d_ref = universe_m_d_ref,
      weights = universe_m_d_ref$weights,
      rel_risk_contr = rp$relative_risk_contribution
    )

    return(rp_results_list)

}
