#' Create group constraints for MTO portfolios
#'
#' @param universe_m_d_ref A dataframe of assets with tickers, is_eligible, final_signal columns and also those generated by application of constraints policies in filter_stock_universe
#' @param concentration_constraints_policy A named list containing up to four elements:
#' - `benchmark`: A character vector describing the benchmark to be used to apply constraint.
#' Must have a correspondence in `benchmark_weights_m_d_ref`
#' - `max_abs_active_individual_weight`: The maximum absolute individual active weights.
#' - `max_abs_active_sector_weight`: The maximum absolute sector active weight used for creating group constraints in `generate_sector_constraints`.
#' If a given sector has no eligible stock, the one with the greatest signal will be automatically promoted.
#' Note that, in the context of `generate_sector_constraints`, a `benchmark_weights_m_d_ref` data frame must also be supplied.
#' @param groups_m_d_ref A data frame containing columns for id, tickers, dates, and sector classification columns following a given classification method.
#' All tickers in the current stock universe must have a unique correspondence in the data frame.
#' @param benchmark_weights_m_d_ref A data frame containing columns for id, tickers, dates, and current benchmark weights columns.
#' All tickers in the current stock universe must have a unique correspondence in this data frame.
#' @return
#' @export
#'
generate_group_constraints <- function(universe_m_d_ref, concentration_constraint_policy, groups_m_d_ref, verbose = TRUE){

  #Generate benchmark_group_weights
  ###################################
  selected_benchmark <- concentration_constraint_policy$benchmark #get benchmark
  groups <- colnames(groups_m_d_ref)[-c(1:3)] #set groups (grouping levels)
  group_constraint_list <- list() #generate list to store group max and min
  eligible_assets_group_membership_list <- list() #generate list to store who belongs to each group

  #Check
  if(is.null(groups_m_d_ref)){
    stop("groups_m_d_ref must be different from NULL in order to implement group constraints")
  }
  if(any(!dplyr::pull(universe_m_d_ref, tickers) %in% dplyr::pull(groups_m_d_ref, tickers))){
    stop("Some tickers in universe_m_d_ref are not present in groups_m_d_ref")
  }

  for(i in 1:length(groups)){
    ##Get original group_vector
    current_group_m_d_ref <- groups_m_d_ref[, c("tickers", groups[i])]

    ##Get benchmark weight
    current_group_m_d_ref <- dplyr::left_join(
      dplyr::select(universe_m_d_ref, tickers, !!rlang::sym(paste0(selected_benchmark, "_bench_weights")), is_eligible), #Dynamically evaluate expression
      current_group_m_d_ref,
      by = "tickers"
    )

    ##Change name to easy manipulation
    colnames(current_group_m_d_ref) <- c("tickers", "benchmark_weight", "is_eligible", "group")
    current_group_m_d_ref <- current_group_m_d_ref %>% dplyr::select(tickers, group, benchmark_weight, is_eligible)

    ##Get group weights in benchmark and re-order alphabetically
    group_concentration_constraints <- current_group_m_d_ref %>% dplyr::group_by(group) %>% #Group by group
      dplyr::summarise(group_benchmark_weights = sum(benchmark_weight)) #Sum group weights

      ###Check if benchmark weights sum to 1
      if(sum(group_concentration_constraints$group_benchmark_weights) - 1 > 0.02){
        stop("Error in generating group constraints. Benchmark weights do not sum to 1.")
      }

    ###Max
    group_concentration_constraints$max_weight <- pmin(group_concentration_constraints$group_benchmark_weights +
                                                         concentration_constraint_policy$max_abs_active_group_weight[i], 1)
    ###Min
    group_concentration_constraints$min_weight <- pmax(group_concentration_constraints$group_benchmark_weights -
                                                         concentration_constraint_policy$max_abs_active_group_weight[i], 0)

    #Store
    group_constraint_list[[i]] <- group_concentration_constraints

    ##Get which assets belong to each group
    ###Unique groups
    unique_groups <- unique(group_concentration_constraints$group)

    ###Create a list to store who belongs to each group
    eligible_assets_group_membership_list[[i]] <- list()
    eligible_assets_current_group_m_d_ref <- current_group_m_d_ref %>% dplyr::filter(is_eligible == 1)
    for(j in 1:length(unique_groups)){
      eligible_assets_group_membership_list[[i]][[j]] <- which(eligible_assets_current_group_m_d_ref$group == unique_groups[j]) #which assets belong to unique_group[j]?
    }
    ###rename
    names(eligible_assets_group_membership_list[[i]]) <- unique_groups

    ##Re-order so that both lists match
    group_membership_order <- match(group_constraint_list[[i]]$group, names(eligible_assets_group_membership_list[[i]])) #Get order of variables in eligible_assets_group_membership_list
    group_constraint_list[[i]] <- group_constraint_list[[i]][group_membership_order, ] #Make them both equal ordered
  }

  ##rename
  names(eligible_assets_group_membership_list) <- groups
  names(group_constraint_list) <- groups

  ##Create final objects to apss to add.constraints
  eligible_assets_group_membership_list <- do.call(c, eligible_assets_group_membership_list) #Transform into a single list
  group_constraint_max <- unlist(lapply(group_constraint_list, function(df) df$max_weight)) %>% as.numeric #Get vector of max_weights
  group_constraint_min <- unlist(lapply(group_constraint_list, function(df) df$min_weight)) %>% as.numeric #Get vector of max_weights


  ##Return complete obj
  group_constraints_list <- list(
    eligible_assets_group_membership_list = eligible_assets_group_membership_list, #What assets belong to each group
    group_constraint_max = group_constraint_max, #Consolidated groups caps
    group_constraint_min = group_constraint_min #Consolidated groups floors
  )
  return(group_constraints_list)

}

