#' Create individual box constraints for MVO portfolios based on liquidity, concentration and turnover constraints
#'
#' @param universe_m_d_ref A dataframe of assets with tickers, is_eligible, final_signal columns and also those generated by application of constraints policies in classify_investment_universe
#' @param liquidity_constraint_policy Optional. A named list containing objects used to apply liquidity constraints. Possible elements of the list are:
#' - `liquidity_floor_rule`: A character indicating the liquidity classification (e.g., micro_caps, small_caps) used to filter stocks. Stocks with less liquidity than specified in `liquidity_floor_rule` will be considered ineligible.
#'   In the case of the `generate_box_constraints` function, `liquidity_constraint_policy` can also contain:
#' - `liquidity_cap_rule` lists: One or many lists used to create upper bounds for weights based on a liquidity classification. Each list must contain:
#'   - `liquidity_classification`: A character indicating the classification for the cap.
#'   - `liquidity_cap`: A numeric value indicating the cap (upper bound) for stocks with that liquidity classification.
#'   Many liquidity caps might be created, and in this case, each `liquidity_cap_rule` must be identified with a number (e.g., liquidity_cap_rule_1, liquidity_cap_rule_2, and so on).
#' @param turnover_constraint_policy A named list containing objects used to build buffer zones and apply turnover constraints.
#' - Each element will constitute a `buffer_zone`, being a list with three elements:
#'   - `liquidity_classification` element: A liquidity classification (e.g., "micro_caps", "small_caps") for that buffer zone.
#'   - `top_stock_quantile_buffer`: A numeric value indicating a buffer value that relaxes `top_stocks_quantile` for stocks with the specified liquidity classification.
#'   - `turnover_cap`: A numeric value specifying the turnover cap.
#'   Stocks that are less liquid than specified for a buffer zone and have a signal higher than the respective buffer quantile will be considered eligible, even if they do not meet the `liquidity_floor_rule`.
#' @param concentration_constraint_policy A named list containing up to four elements:
#' - `benchmark`: A character vector describing the benchmark to be used to apply constraint.
#' Must have a correspondence in `benchmark_weights_m_d_ref`
#' - `max_abs_active_individual_weight`: The maximum absolute individual active weights.
#' - `max_abs_active_sector_weight`: The maximum absolute sector active weight used for creating group constraints in `generate_sector_constraints`.
#' If a given sector has no eligible stock, the one with the greatest signal will be automatically promoted.
#' @param verbose Logical. If TRUE, the function will print messages indicating the progress of the process.
#' Note that, in the context of `generate_sector_constraints`, a `benchmark_weights_m_d_ref` data frame must also be supplied.
#'
generate_box_constraints <- function(universe_m_d_ref, liquidity_constraint_policy = NULL, turnover_constraint_policy = NULL, concentration_constraint_policy,
                                     verbose = TRUE){
  #Get initial items
  ####################

    ##Eligible Stock universe
    eligible_universe_m_d_ref <- universe_m_d_ref %>% dplyr::filter(is_eligible == 1)

    ##Selected benchmark
      ###Check
      if (is.null(concentration_constraint_policy$benchmark)){
        stop("Please provide a benchmark to apply concentration constraints")
      }

      ###Extract benchmark
      selected_benchmark <- concentration_constraint_policy$benchmark
  ####################

  #Generate eligible_assets_box_constraints_m_d_ref
  ####################
      ##Define a function to select columns if they exist (if they were previously generated by classify_investment_universe)
      select_if_exists <- function(df, cols) {
        df %>% dplyr::select(dplyr::any_of(cols))
      }

      ##Select cols that exist
      eligible_assets_box_constraints_m_d_ref <- eligible_universe_m_d_ref %>% select_if_exists(c("tickers", "liquidity_classification", paste0(selected_benchmark, "_bench_weights"), "bop_port_weights")) %>% #Get only eligible stocks
        dplyr::rename(benchmark_weights = !!rlang::sym(paste0(selected_benchmark, "_bench_weights")))


  ####################

  #Set active_weights_constraints
  ###############################
    ##Get max_abs_weight
      max_abs_weight <- purrr::pluck(concentration_constraint_policy, "max_abs_active_individual_weight", .default = 0)

    ##Create max and min active_weights
      eligible_assets_box_constraints_m_d_ref <- eligible_assets_box_constraints_m_d_ref %>%
        dplyr::mutate(
          active_weights_constraint_max = pmin(benchmark_weights + max_abs_weight, 1), #Benchmark + max_abs
          active_weights_constraint_min = pmax(benchmark_weights - max_abs_weight, 0) #Benchmark - max_abs
        )

  ###############################

  #Set liquidity_cap_constraints
  ################################
  if (!is.null(liquidity_constraint_policy$liquidity_cap_rules)){
    ##Get liquidity_cap_rules
    liquidity_caps <- liquidity_constraint_policy$liquidity_cap_rules
    for (i in seq_along(liquidity_caps)){
      ###Set which stocks are subject to the liquidity_cap
      stocks_subject_to_liquidity_cap <- names(liquidity_caps)[i]

      ###Max weights
      liquidity_constraint_max <- eligible_assets_box_constraints_m_d_ref %>%
        dplyr::filter(liquidity_classification %in% stocks_subject_to_liquidity_cap) %>% #Filter
        dplyr::select(tickers, benchmark_weights) %>% #Select appropriate cols
        dplyr::mutate(!!rlang::sym(paste0("liquidity_cap_rule_", i)) := pmin(benchmark_weights + liquidity_caps[i], 1)) %>% #Create new col
        dplyr::select(-benchmark_weights) #unselect
      colnames(liquidity_constraint_max)[2] <- paste0(colnames(liquidity_constraint_max)[2], "_max") #Rename
      ###Left Join
      eligible_assets_box_constraints_m_d_ref <- dplyr::left_join(eligible_assets_box_constraints_m_d_ref, liquidity_constraint_max, by = "tickers")
    }
  }
  ################################

  #Set turnover_constraints
  ################################
  if (!is.null(turnover_constraint_policy)){
    ##Get turnover_cap_rules
    turnover_caps <- turnover_constraint_policy$turnover_cap_rules
    for (i in seq_along(turnover_caps)){
      ###Set which stocks are subject to the turnover_constraint_policy
      stocks_subject_to_turnover_cap_rule <- names(turnover_caps)[i]

      ###Max weights
      turnover_constraint_max <- eligible_assets_box_constraints_m_d_ref %>%
        dplyr::filter(liquidity_classification %in% stocks_subject_to_turnover_cap_rule) %>% #Filter
        dplyr::select(tickers, bop_port_weights) %>% #Select appropriate columns
        dplyr::mutate(!!rlang::sym(paste0("buffer_zone_", i)) := pmin(bop_port_weights + turnover_caps[i], 1)) %>% #Create new col
        dplyr::select(-bop_port_weights) #Unselect
      colnames(turnover_constraint_max)[2] <- paste0(colnames(turnover_constraint_max)[2], "_max") #Rename
      ###Left Join
      eligible_assets_box_constraints_m_d_ref <- dplyr::left_join(eligible_assets_box_constraints_m_d_ref, turnover_constraint_max, by = "tickers")

      ###Min weights
      turnover_constraint_min <- eligible_assets_box_constraints_m_d_ref %>%
        dplyr::filter(liquidity_classification %in% stocks_subject_to_turnover_cap_rule) %>% #Filter
        dplyr::select(tickers, bop_port_weights) %>% #Select appropriate columns
        dplyr::mutate(!!rlang::sym(paste0("buffer_zone_", i)) := pmax(bop_port_weights - turnover_caps[i], 0)) %>% #Create new col
        dplyr::select(-bop_port_weights)
      colnames(turnover_constraint_min)[2] <- paste0(colnames(turnover_constraint_min)[2], "_min") #Rename
      ###Left Join
      eligible_assets_box_constraints_m_d_ref <- dplyr::left_join(eligible_assets_box_constraints_m_d_ref, turnover_constraint_min, by = "tickers")
    }
  }
  ################################

  #Set max and min consolidated weights
  ######################################
  ##Calculate active weights
  ###Max (A stock will never be able to have a maximum weight smaller than benchmark_weight)
  eligible_assets_max_active_weights = (eligible_assets_box_constraints_m_d_ref[grep("_max$", names(eligible_assets_box_constraints_m_d_ref), value = TRUE)] -
                                        eligible_assets_box_constraints_m_d_ref$benchmark_weights) %>%
        apply(1, function(x) max(min(x, na.rm = TRUE), 0, na.rm = TRUE)) #Min max_active_weights must be zero


  ###Min (A stock will never be able to have a minimum weight larger than benchmark_weight)
  eligible_assets_min_active_weights = (eligible_assets_box_constraints_m_d_ref[grep("_min$", names(eligible_assets_box_constraints_m_d_ref), value = TRUE)] -
                                        eligible_assets_box_constraints_m_d_ref$benchmark_weights) %>%
        apply(1, function(x) min(max(x, na.rm = TRUE), 0, na.rm = TRUE)) #Max min_active_weights must be zero

  ###Create wiggle room if max_weight = min_weight
  #Check if there are equalities
  max_active_weight_equal_min_active_weight <- which(eligible_assets_max_active_weights <= 0.002 & eligible_assets_min_active_weights >= -0.002)
    ###Create wiggle
    if (length(max_active_weight_equal_min_active_weight) != 0){
      ####Message
      if (verbose){
        cat("\n")
        cat(crayon::yellow(paste("Application of box constraints introduced equalities between max and min constraints. Creating wiggle room to prevent problems during optimization.")))
      }
    ###Set wiggle
      eligible_assets_max_active_weights[max_active_weight_equal_min_active_weight] <- eligible_assets_max_active_weights[max_active_weight_equal_min_active_weight] + 0.002
      eligible_assets_min_active_weights[max_active_weight_equal_min_active_weight] <- eligible_assets_min_active_weights[max_active_weight_equal_min_active_weight] - 0.002
    }

  #Set weights
  eligible_assets_box_constraints_m_d_ref$max_weight <- eligible_assets_box_constraints_m_d_ref$benchmark_weights + eligible_assets_max_active_weights #Set max weights
  eligible_assets_box_constraints_m_d_ref$min_weight <- eligible_assets_box_constraints_m_d_ref$benchmark_weights + eligible_assets_min_active_weights #Set min weights

  ######################################
  #Merge
    eligible_universe_m_d_ref <- dplyr::left_join(eligible_universe_m_d_ref,
                                                  eligible_assets_box_constraints_m_d_ref %>% dplyr::select(tickers, max_weight, min_weight), #Select only those cols
                                                  by = "tickers")


  #Return eligible_universe_m_d_ref
  return(eligible_universe_m_d_ref)

}
