
#' Applies a buffer rule based on the creation of a buffer zone for illiquid stocks
#'
#' This rule is applied to reduce portfolio turnover and transaction costs.
#'
#' @param stock_universe_m_d_ref A data frame of selected signals generated by the `generate_signal_matrix` function.
#' @param top_stocks_quantile_buffer Numeric value indicating the quantile to apply the buffer rule.
#'  Stocks in this quantile and pre-rebalancing portfolio will be included in the `filtered_stock_universe` if they meet the buffer rule policy.
#' @param updated_port_weights_m_lstd_ref  A data frame containing columns for id, tickers, dates and weights from the old portfolio (pre-rebalancing)
#' All tickers in current stock universe must have a unique correspondence in this data frame.
#' @param liquidity_m_d_ref A data frame (similar to `features_m_df`) containing columns for id, tickers, dates, and one or more market liquidity measures (e.g., inflation-adjusted mean financial volume).
#' All tickers in current stock universe must have a unique correspondence in this data frame.
#' @param liquidity_floor_cutoffs A list of named vectors containing cutoff values for liquidity metrics specified in `liquidity_m_d_ref`.
#' The names should match the metrics and values should be the minimum acceptable values (adjust for inflation)
#' Elements should be: "micro_caps", "small_caps", "mid_caps" and "large_caps"
#' Classification should be in ascending order (from lest liquid to most liquid) for all metrics.
#' @param turnover_cap_rule Character string specifying the buffer rule target (one of "micro_caps", "small_caps", "mid_caps", "large_caps", "mega_caps").
#' Stocks that are less liquid than `turnover_cap_rule` and that are included in the buffer_zone will be promoted.
#' Stocks meeting this rule will be included in the `filtered_stock_universe` even if they fail the liquidity floor rule.
#'
#'
apply_turnover_cap_rule <- function(stock_universe_m_d_ref,
                                    eligibility_quantile_range, quantile_range_buffer,
                                    updated_port_weights_m_lstd_ref,
                                    liquidity_m_d_ref, liquidity_floor_cutoffs, turnover_cap_rule, verbose = TRUE){

  ##Checks
  ###########
  ##Check possibilities for turnover_cap_rule
  if(!turnover_cap_rule %in% c("micro_caps", "small_caps", "mid_caps", "large_caps", "mega_caps")){
    stop("turnover_cap_rule not supported")
  }

  ############

  ##Get objects
  ################
  ###Init data frame without bop_port_weights in case it is a second run
  stock_universe_m_d_ref <- stock_universe_m_d_ref %>% dplyr::select(-dplyr::any_of("bop_port_weights"))
  ###Get liquidity metrics names
  liquidity_metrics <- colnames(liquidity_floor_cutoffs)[-1] #Get name of metrics

  ################

  ##Buffer Zone
  #################
  ###Enlarge eligibility_quantile_range according to quantile_range_buffer
  buffered_quantile_range <- sort(eligibility_quantile_range)
  buffered_quantile_range[1] <- max(eligibility_quantile_range[1] - quantile_range_buffer, 0)
  buffered_quantile_range[2] <- min(eligibility_quantile_range[2] + quantile_range_buffer, 1)

  ###Is in top quantile buffer?
  turnover_cap_rule_m_d_ref <- classify_stocks_pre_eligibility(
    stock_universe_m_d_ref = stock_universe_m_d_ref,
    eligibility_quantile_range = buffered_quantile_range) %>%
    dplyr::rename(is_in_buffered_quantile_range = pre_eligible_assets)

  ###Was in old_portfolio?
  turnover_cap_rule_m_d_ref <- turnover_cap_rule_m_d_ref %>%
    dplyr::left_join(updated_port_weights_m_lstd_ref %>% dplyr::select(-id, -dates), by = "tickers") %>% #Get old weights
    dplyr::select(id, tickers, dates, is_in_buffered_quantile_range, bop_port_weights) #Select only those info

  ####Replace NAs (new stocks) for 0
  turnover_cap_rule_m_d_ref <- turnover_cap_rule_m_d_ref %>%
    dplyr::mutate(bop_port_weights = tidyr::replace_na(bop_port_weights, 0))

  ####Create column to represent if stock was in old portfolio
  turnover_cap_rule_m_d_ref <- turnover_cap_rule_m_d_ref %>%
    dplyr::mutate(was_in_old_portfolio = dplyr::if_else(bop_port_weights > 0, 1L, 0L))

  #################

  ##Applies buffer rule
  #################
  ###Meets buffer rule policy?
  ####Gets stocks which liquidity_classification is equal to turnover_cap_rule
  turnover_cap_rule_m_d_ref <- turnover_cap_rule_m_d_ref %>%
    dplyr::mutate(
      does_liquidity_meets_turnover_cap_rule = dplyr::if_else(
        classify_stock_liquidity(
          liquidity_floor_cutoffs = liquidity_floor_cutoffs, #Liquidity classification thresholds
          liquidity_m_df = liquidity_m_d_ref, #Liquidity data
          liquidity_floor_rule = turnover_cap_rule, #Classification rule
          apply_liquidity_floor_rule = FALSE,
          filter_out_liquidity_floor_rule = FALSE
        ) %>% dplyr::pull(liquidity_classification) == turnover_cap_rule, #Compare classification
        1L, #True: meets the rule
        0L  #False: does not meet the rule
      )
    )

  ###Apply buffer rule
  turnover_cap_rule_m_d_ref <- turnover_cap_rule_m_d_ref %>%
    dplyr::mutate(
      turnover_cap_rule = as.integer(
        is_in_buffered_quantile_range == 1 &
          was_in_old_portfolio == 1 &
          does_liquidity_meets_turnover_cap_rule == 1)
    )


  #################

  #Message
  buffered_stocks <- turnover_cap_rule_m_d_ref %>% dplyr::filter(turnover_cap_rule == 1) %>% dplyr::pull(tickers)
  if(verbose){
    if (length(buffered_stocks > 0)){
      cat("\n")
      cat(paste0("The following ", turnover_cap_rule, " stocks belong to the buffer_zone and will be kept:"))
      cat("\n")
      cat(buffered_stocks)
      cat("\n")
    } else {
      cat("\n")
      cat(paste0("No ", turnover_cap_rule, " stocks belong to the buffer_zone."))
      cat("\n")
    }
  }


  ###Return object
  return(turnover_cap_rule_m_d_ref)

}
