#' Create sector constraints for MTO portfolios
#'
#' @param current_stock_universe_df A dataframe of stocks with tickers, is_stock_eligible, final_signal columns and also those generated by application of constraints policies in filter_stock_universe
#' @param sectors_constraint_policy A named list with one or several elements, in which each element is a data frame with sector_classification, max and min sector weights.
#' Each element's name must correspond to the corresponding sector classification name, so that the user can implement sectors, subsectors, segments restrictions.
#' Each dataframe must have columns labeled as sector, max_weight and min_weight.
#' @param sectors_m_df A dataframe with id, tickers and dates with dummy sectors classifications to be used to fill NAs
#' @return
#' @export
#'
generate_sector_constraints <- function(current_stock_universe_df, sectors_constraint_policy, sectors_m_df){

  #Generate benchmark_sector_weights
  ###################################
    ##Get original sector_vector
    sectors_df <- undummy_sector_features(sectors_m_df)

    ##Add benchmark_weights
    sectors_df <- left_join(sectors_df,
                            current_stock_universe_df %>% dplyr::select(tickers, benchmark_weights),
                            by = "tickers")

    ##Calculate benchmark_sectors_weights
    benchmark_sectors_df <- sectors_df %>% dplyr::group_by(sectors) %>% dplyr::summarise(benchmark_sector_weights = sum(benchmark_weights, na.rm = TRUE))
  ##################################




  #Eligible Stock universe
  eligible_stocks_universe_df <- current_stock_universe_df %>% dplyr::filter(is_stock_eligible == 1)


}

