#' Fit a Bayesian Hierarchical Regression Model and Summarize Posterior Metrics
#'
#' This function fits a Bayesian hierarchical regression model using the `brms` package and computes posterior summary
#' statistics for signal-level metrics. The model captures signal clustering within themes and provides detailed
#' posterior metrics for use in performance analysis.
#'
#' @param signal_universe_m_d_ref A data frame containing the signal universe. If provided, data in this object will be updated with posteriors.
#'
#' @param selected_backtest_returns_corrected_positions_m_xts_upd_ref A xts containing the backtest returns data for various signals.
#'
#' @param selected_market_factor_proxy_m_xts_upd_ref A numeric vector containing benchmark returns data. The vector will be recycled
#'   to match the length of the backtest returns data.
#'
#' @param elected_priors An object of class `brmsprior` containing priors for the Bayesian model, such as those generated by the
#'   \code{derive_informative_priors_from_data} function or provided directly by the user.
#'
#' @param selected_signal_themes_m_d_ref A data frame containing metadata about signals. This data frame should include:
#'   - `tickers`: Signal identifiers matching those in `selected_backtest_returns_corrected_positions_m_xts_upd_ref`.
#'   - `theme`: Group membership for each signal, defining the clusters for the Bayesian hierarchical model.
#'   - `dates`: Dates corresponding to the backtest data.
#'   This input ensures proper alignment between signals and their associated themes.
#'
#' @param selected_backtest_returns_corrected_positions_m_upd_ref An already processed `selected_backtest_returns_corrected_positions_m_xts_upd_ref`.
#' This data.frame is already in long format and contemplates both the `selected_market_factor_proxy_m_xts_upd_ref` and the
#' `selected_signal_themes_m_d_ref` theme data.
#'
#' @param model_spec_theme_level A character string specifying the desired Bayesian model structure.
#'   Options include:
#'   - `"random_intercept_fixed_slope"`: Includes random effects for the intercept at the theme level.
#'   - `"theme_specific_intercept_fixed_slope"`: Uses fixed intercepts for each theme.
#'   - `"theme_specific_intercept_theme_specific_slope"`: Includes fixed intercepts and slopes for each theme.
#'   - `"fixed_intercept_fixed_slope"`: Omits theme-level intercepts but includes random effects at the theme:signal level.
#'
#' @param chains An integer specifying the number of Markov chains to run. Defaults to `4`.
#' @param iter An integer specifying the number of iterations per chain. Defaults to `2000`.
#' @param warmup An integer specifying the number of warmup iterations. Defaults to `1000`.
#' @param thin An integer specifying the thinning interval. Defaults to `1`.
#' @param seed An integer, or `NA`, specifying the random seed for reproducibility. No default; passed through from the caller.
#' @param adapt_delta A numeric value between 0 and 1 specifying the target acceptance rate for the Hamiltonian Monte Carlo sampler.
#' @param verbose A logical indicating whether to display progress messages during the model fitting process. Defaults to `TRUE`.
#' @param parallel A logical indicating whether to enable parallel computation using `future`. Defaults to `TRUE`.
#'
#' @return A named list containing:
#'   - `brm_model`: A `brmsfit` object containing the fitted Bayesian model. This object includes posterior distributions,
#'     parameter estimates, diagnostics, and other details of the model fit.
#'   - `signal_universe_m_d_ref`: A data frame containing the updated `signal_universe_m_d_ref` with posterior summary statistics,
#'     or `NULL` if `signal_universe_m_d_ref` was `NULL`.
#'   - `posterior_draws_summaries`: A list of median/89\% CI summaries for the intercept, slope, and scale parameters
#'     (see `summarize_posteriors_draws()`), or `NULL` if `signal_universe_m_d_ref` was `NULL`.
#'
#' @details
#' The function performs the following steps:
#' 1. **Preprocessing**: Converts the backtest returns data into long format, merges metadata about signals and themes,
#'    and adds the market factor proxy.
#' 2. **Formula Specification**: Defines the Bayesian model formula based on the chosen `model_spec_theme_level`.
#' 3. **Model Fitting**: Fits the Bayesian model using the `brm` function from the `brms` package, incorporating the
#'    provided priors and prepared data.
#' 4. **Posterior Summarization**: Extracts posterior draws and computes signal-level metrics such as alphas, betas,
#'    sigmas, active returns, tracking errors, information ratios (IR), appraisal ratios (AP), and Treynor ratios.
#'    Updates the `signal_universe_m_d_ref` data frame with these metrics.
#'
#' This hierarchical approach allows the model to capture both global (theme-level) and local (signal-level) effects
#' while leveraging the flexibility of Bayesian regression. The inclusion of posterior metrics enables deeper
#' performance analysis of signals.
#'
#'
fit_bayesian_hierarchical_model <- function(signal_universe_m_d_ref, selected_backtest_returns_corrected_positions_m_xts_upd_ref, selected_market_factor_proxy_m_xts_upd_ref, #Data
                                            selected_backtest_returns_corrected_positions_m_upd_ref = NULL,
                                            elected_priors, selected_signal_themes_m_d_ref, model_spec_theme_level, #Hierarhical Model spec
                                            chains, iter, warmup, thin, seed, adapt_delta, #brm parameters (Monte Carlo Markov Chains - MCMC settings)
                                            verbose, parallel){


  #Prepare objects
  ########################
  brm_model_inputs_list <- prepare_hierarchical_model_inputs(
    selected_backtest_returns_corrected_positions_m_xts_upd_ref = selected_backtest_returns_corrected_positions_m_xts_upd_ref,
    selected_market_factor_proxy_m_xts_upd_ref = selected_market_factor_proxy_m_xts_upd_ref,
    selected_backtest_returns_corrected_positions_m_upd_ref = NULL,
    selected_signal_themes_m_d_ref = selected_signal_themes_m_d_ref,
    model_spec_theme_level = model_spec_theme_level
  )

  #Get m_upd_ref backtest data and brm formula
  selected_backtest_returns_corrected_positions_m_upd_ref <- brm_model_inputs_list$selected_backtest_returns_corrected_positions_m_upd_ref
  brm_formula <- brm_model_inputs_list$formula

  #Check for non-conformity in theme-specific priors and inform user
  #In case there any exceding priors, brms will warn
  if (model_spec_theme_level %in% c("theme_specific_intercept_fixed_slope", "theme_specific_intercept_theme_specific_slope")){
    ##Get current themes
    current_themes <- selected_signal_themes_m_d_ref %>% dplyr::pull(theme) %>% unique()
    ##Expected priors
    expected_theme_priors <- switch(
      model_spec_theme_level,
      "theme_specific_intercept_fixed_slope" = paste0("theme", current_themes),
      "theme_specific_intercept_theme_specific_slope" = c(paste0("theme", current_themes), paste0("theme", current_themes, ":market_factor_proxy"))
    )
    ##Check for missing
    priors_to_check <- elected_priors %>% dplyr::filter(stringr::str_detect(coef, "^theme\\w+(:market_factor_proxy)?$")) %>% dplyr::pull(coef)
    if (any(!expected_theme_priors %in% priors_to_check)){
      warning("Some theme-specific priors are missing. Using brms default priors for the following: ",
              paste(setdiff(expected_theme_priors, priors_to_check), collapse = ", "))
    }
    ##Check for extra
    if (any(!priors_to_check %in% expected_theme_priors)){
      warning("Some extra theme-specific priors are provided. These will be ignored: ",
              paste(setdiff(priors_to_check, expected_theme_priors), collapse = ", "))

      ###Exclude extra prior
      extra_prior <- setdiff(priors_to_check, expected_theme_priors) #Identify extra priors
      elected_priors <- elected_priors %>% dplyr::filter(!coef %in% extra_prior) #Filter them out
    }
  }


  #Fit brm
  ########################

  ###Fit model
  brm_model <- brms::brm(
    brm_formula,
    #Priors
    prior = elected_priors,
    #Data
    data = selected_backtest_returns_corrected_positions_m_upd_ref,
    #Parallelization
    future = parallel,
    #MCMC
    chains = chains, iter = iter, warmup = warmup, thin = thin, seed = seed,
    control = list(adapt_delta = adapt_delta)
  )
  ########################

  #Get Posteriors
  #############################################

  #Update signal_universe_m_d_ref with posterior statistics
  if (!is.null(signal_universe_m_d_ref)){
  posteriors_results_list <- summarize_posteriors_draws(
    brm_model = brm_model, #brms model
    signal_universe_m_d_ref = signal_universe_m_d_ref, #Signal Universe
    model_spec_theme_level = model_spec_theme_level, #Model spec
    selected_signal_themes_m_d_ref = selected_signal_themes_m_d_ref) #Groups
  } else {
    posteriors_results_list <- NULL
  }
  #############################################

  #Final Obj
  bayesian_fit_results_list <- list(
    brm_model = brm_model,
    signal_universe_m_d_ref = posteriors_results_list$signal_universe_m_d_ref,
    posterior_draws_summaries = posteriors_results_list$posterior_draws_summaries
  )

  return(bayesian_fit_results_list)
}
