#' Create a cap_weighted portfolio
#'
#' @param current_stock_universe_df A dataframe with tickers, is_stock_eligible and final_signal columns generated by filter_stock_universe
#' @param liquidity_m_d_ref A data frame (similar to `features_m_df`) containing columns for id, tickers, dates, and one or more market liquidity measures (e.g., inflation-adjusted mean financial volume).
#' All tickers in current stock universe must have a unique correspondence in this data frame.
#' @param cap_weighting_metric cap weighting metric in liquidity_m_d_ref to be used to weight stocks when portfolio_construction_method is CW
#' @param lower_quantile_winsorization lower quantile to winsorize cap_weighting_metric
#' @param upper_quantile_winsorization upper quantile to winsorize cap_weighting_metric
#'
#' @return
#' @export
#'
#' @examples
create_cap_scaled_portfolio <- function(universe_m_d_ref, liquidity_m_d_ref, cap_weighting_metric, lower_quantile_winsorization = 0.025, upper_quantile_winsorization = 0.975,
                                        verbose = TRUE){

  #Message
  if(verbose){
    tictoc::tic()
    cat("\n")
    cat(paste0("Deriving weights through CS. Using ", cap_weighting_metric, " as cap-weighting metric."))
  }

  #Create cs_weights object
  cs_weights <- universe_m_d_ref %>% dplyr::select(tickers, is_eligible, exp_ret_score) %>%
    dplyr::left_join(liquidity_m_d_ref %>% dplyr::select(tickers, !!rlang::sym(cap_weighting_metric)), by = "tickers") #Merge with liquidity_m_d_ref

  #Create cap score (cw_weighting_metric signal_transformed)
  cs_weights <- cs_weights %>% dplyr::mutate(cap_score = signal_transform(
    !!rlang::sym(cap_weighting_metric),
    lower_quantile_winsorization = lower_quantile_winsorization,
    upper_quantile_winsorization = upper_quantile_winsorization
  ))


  #Create CS Weights
  cs_weights <- cs_weights %>%
    dplyr::mutate(weights = dplyr::if_else(is_eligible == 1, #When is_eligible is 1
        (exp_ret_score * cap_score) / sum((exp_ret_score * cap_score)[is_eligible == 1]), #Calculate weight based on cap-score
        0 #Else, is 0
      )
    ) %>%
    # Remove columns we no longer need in final output
    dplyr::select(-{{cap_weighting_metric}}, -is_eligible, -exp_ret_score)

  #Merge with universe_m_d_ref
  universe_m_d_ref <- universe_m_d_ref %>% dplyr::left_join(cs_weights, by = "tickers")

  #Check for weights different from 1
  if (abs(sum(universe_m_d_ref$weights) - 1) > 0.02){
    stop("Weights do not sum to 1")
  }

  #Message
  if(verbose){
    cat("\n")
    cat(crayon::green(paste("Cap-scaled weights succesfully defined")))
    cat("\n")
    elapsed_time <- tictoc::toc()
  }

  #Return
  cs_results_list <- list(
    universe_m_d_ref = universe_m_d_ref,
    weights = universe_m_d_ref$weights,
    cap_weighting_metric = universe_m_d_ref$cap_weighting_metric,
    exp_ret_score = universe_m_d_ref$exp_ret_score
  )

  return(cs_results_list)
}
