#' Create a risk parity portfolio
#'
#' @param universe_m_d_ref A dataframe with tickers, is_eligible and final_signal columns generated by filter_stock_universe
#' @param covariance_matrix The covariance matrix of all eligible stocks in universe_m_d_ref.
#' @param rp_method The method used to calculate the risk parity weights. Default is "cyclical-spinu". See riskParityPortfolio::riskParityPortfolio for more options.
#' @param exp_ret_score_tilt One of 'none', 'inner' or 'final', indicating whether to apply the exp_ret_score tilt during the risk parity optimization ('inner'), after the optimization ('final'), or not at all ('none').
#' @param exp_ret_score_tilt_eta The numeric tilt to apply to the risk parity weights based on the exp_ret_score column in universe_m_d_ref. If NULL, no tilt is applied.
#' @param verbose If TRUE, will print messages to the console
create_risk_parity_portfolio <- function(universe_m_d_ref, covariance_matrix,
                                         rp_method = "cyclical-spinu",
                                         exp_ret_score_tilt = NULL,
                                         exp_ret_score_tilt_eta = NULL,
                                         verbose = TRUE){

  # Initial Setup---------------------------------------------------------------

   ## Message
   if(verbose){
     tictoc::tic()
     cat("\n")
     cat("Deriving weights through RP...")
     cat("\n")
     cat("RP method: ", rp_method, "\n")
     if (!is.null(exp_ret_score_tilt)) cat("Exp Ret Score Tilt: ", exp_ret_score_tilt, "\n")
     if (!is.null(exp_ret_score_tilt_eta)) cat("Exp Ret Score Tilt Eta: ", exp_ret_score_tilt_eta, "\n")

   }

    ### Defensively check if exp_ret_score column exists in universe_m_df
    if (!is.null(exp_ret_score_tilt) && exp_ret_score_tilt != "none" &&
        !("exp_ret_score" %in% colnames(universe_m_d_ref))) {
      stop("exp_ret_score column is not present in universe_m_d_ref")
    }

   ### Defensively check for alignment of cov and eligible tickers
   if (!identical(rownames(covariance_matrix),
                  universe_m_d_ref %>%
                   dplyr::filter(is_eligible == 1L) %>%
                   dplyr::pull(tickers)
                  )) {
     stop("covariance_matrix row/col names must exactly match eligible tickers order")
   }


  # Tilted RP-------------------------------------------------------------------
  if (!is.null(exp_ret_score_tilt_eta) &&
      !is.null(exp_ret_score_tilt) && exp_ret_score_tilt == "inner") {

    ## Create rp_weights object depending on existence of a exp_ret_score_tilt_eta

      ### Apply rp with exp_ret_score_tilt_eta
      rp <- riskParityPortfolio::riskParityPortfolio(
        #### Cov
        Sigma = covariance_matrix,
        #### Tilt
        mu = universe_m_d_ref$exp_ret_score[
          match(rownames(covariance_matrix), universe_m_d_ref$tickers)],
        lmd_mu = exp_ret_score_tilt_eta,
        #### Method
        method_init = rp_method
      )

  # Traditional RP---------------------------------------------------------------
  } else {

    ### Apply rp without exp_ret_score_tilt
    rp <- riskParityPortfolio::riskParityPortfolio(
      Sigma = covariance_matrix,
      method_init = rp_method
    )

  }

  # Apply final tilt if specified------------------------------------------------
  if (!is.null(exp_ret_score_tilt_eta) &&
      !is.null(exp_ret_score_tilt) && exp_ret_score_tilt == "final") {

    exp_ret_scores <- universe_m_d_ref$exp_ret_score[
      match(rownames(covariance_matrix), universe_m_d_ref$tickers)] %>%
      setNames(rownames(covariance_matrix))

    ### Apply final tilt to weights
    rp$w <- rp$w * ( exp_ret_scores ^ exp_ret_score_tilt_eta )
    rp$w <- rp$w / sum(rp$w) # Normalize to sum to 1

  }

  # Return weights---------------------------------------------------------------
    ## Get weights and RRC
    rp_weights <- data.frame(tickers = names(rp$w), weights = rp$w)

    ## Merge with current_stock_universe
    universe_m_d_ref <- dplyr::left_join(universe_m_d_ref, rp_weights, by = "tickers")

    ## Replace NAs with zeros
    universe_m_d_ref[which(is.na(universe_m_d_ref$weights)),"weights"] <- 0

    ## Check for weights different from 1
    if (abs(sum(universe_m_d_ref$weights) - 1) > 1e-6){
      stop("Weights do not sum to 1")
    }

    ## Message
    if(verbose){
      cat("\n")
      cat(crayon::green(paste("Risk Parity weights succesfully defined")))
      cat("\n")
      tictoc::toc()
    }

    ## Return
    rp_results_list <- list(
      universe_m_d_ref = universe_m_d_ref,
      weights = universe_m_d_ref$weights,
      rel_risk_contr = rp$relative_risk_contribution
    )

    return(rp_results_list)

}
